@extends('layout.default')

@section('head')
@parent
<title>Privacy Policy | Mycollegeadda</title>
@stop
      
@section('content')
<section class="uk-container uk-container-center uk-text-justify uk-margin-large-top">
				<h2>Privacy Policy</h2>
				<hr>
        <article>
        <p>
          Mycollegeadda ("Mycollegeadda" or "we" or "Mycollegeadda.com") is dedicated to protecting your personal information and informing you about how we use it. This privacy policy applies to transactions and activities and data gathered on any Mycollegeadda service (the "Site") including but not limited to (1) the services available under the domain and sub-domains of www.Mycollegeadda.com and (2) any Mycollegeadda "widget" or service embedded on a third-party website such as a university, company, or other organization. Please review this privacy policy periodically as we may revise it without notice. This privacy policy was last revised on January 1, 2015. Each time you use the Site or provide us with information, by doing so you are accepting the practices described in this privacy policy at that time.
        </p>
        <h3> Your IP Address</h3>
        <p>
          Like most e-commerce Websites, each time you visit the Site, we automatically collect your IP address and the web page from which you came. In order to administer and optimize the Site for you and to diagnose problems with our Site, we use your IP address to help identify you and to gather broad demographic information about you.
        </p>
        <h3> Cookies</h3>
        <p>
        Mycollegeadda.com collects anonymous information through cookies. A cookie is a small piece of data containing a unique identification number that is sent to your browser from a Web server, and is stored on your computer's hard drive. The unique ID number identifies your browser to Mycollegeadda.com's computers whenever you visit. Cookies do not enable anyone to access personally identifiable information that you have not already given us. Mycollegeadda.com primarily uses cookies to connect members with account information stored on Mycollegeadda.com's computers. This helps Mycollegeadda.com deliver better and more personalized service. Mycollegeadda.com also uses cookies to estimate Mycollegeadda.com's audience size for advertisers; to assist in processing items in your shopping basket; to track the number of entries in Mycollegeadda.com promotions, sweepstakes and contests; to identify the areas of the site you visit; to hold session information; and to track user preferences.
        Cookies are part of the technology implemented by your browser. Most browsers are initially set up to accept cookies. You can reset your browser to either notify you when you have received a cookie, or to refuse them all together.
        Mycollegeadda.com relies on cookies to preserve the Mycollegeadda.com identity you have created while logged on. If you set your browser to disable cookies, you may not be able to access certain areas on the Site.
        </p>
        <h3> Data We Collect From You</h3>
        <p>
          In order to operate the Site and to provide you with information about products or services that may be of interest to you, we may collect "personal information" (i.e. information that could be used to contact you directly (without using the Site) such as full name, postal address, phone number, credit/debit card information, or email address) or "demographic information" (i.e. information that you submit, or that we collect, that is not personal information; this may include, but is not limited to, zip code, hometown, gender, username, age/birth date, browsing history information, searching history information, and registration history information. Demographic information is divided into two categories: 1) "non-public information", which consists of one-on-one communications between you and other users of the Site; and 2) "public information", which consists of all other demographic information. Please note that nowhere on the Site do we knowingly collect, keep or maintain personal information from children under the age of 18, as we require that all users represent to us that they are at least 18 years old.
        </p>
        <h3> How We Use Personal Information</h3>
        <p>
          We use your email address and your other personal information to help us efficiently operate the Site, to contact you in connection with your transactions and other activities on the Site (including, but not limited to, confirmation emails, or important news that could affect your relationship with the Site). These types of communications, are known as "Operational Communications." In some cases, Operational Communications may also contain commercial messages, such as banner ads and special offers.
        To operate the Site, including processing your transactions and supporting your activities on the Site, we may share your personal information with our agents, representatives, contractors and service providers so they can provide us with support services such as email origination, receipt or support services, customer relationship management services, and order fulfillment. We require these entities not to use your information for any other purpose.
        By purchasing, or registering or making reservations for, products or services offered or sponsored by third parties on the Site, or electing to receive communications (such as emails or material by mail) or electing to participate in contests, sweepstakes or other programs (such as discount or rewards programs), offered or sponsored by third parties on the Site, you consent to our providing your personal information to those third parties. Those third parties may use your personal information in accordance with their own privacy policies. You will need to contact those third parties to instruct them directly regarding your preferences for the use of your personal information by them. Additionally, you agree that we may use and disclose all such information so submitted to such third parties in the same manner in which we are entitled to use and disclose any other information you submit to us.
        Any third party with whom we are allowed to share your personal information is authorized to use your personal information in accordance with our contractual arrangements with such third parties and in accordance with their own privacy policies, over which we have no control, and you agree that we are not responsible or liable for any of their actions or omissions. Those who contact you will need to be instructed directly by you regarding your preferences for the use of your personal information by them.
        </p>
        <h3> How We Use Demographic Data</h3>
        <p>
          We may review all demographic Data. We may use public information to enable other users to search your profile, to determine whether your posted details fit other user's requirements, and to communicate with you. We may use demographic information to tailor the Site and communications to your interests. We may also share demographic information with advertisers on an anonymous and aggregated basis (i.e., without telling the advertisers your identity). One of the reasons we may do this is to increase the likelihood that our advertisers' goods and services will appeal to you as a Mycollegeadda user. Our sharing of demographic information with advertisers is anonymous (i.e., we do not tell advertisers which particular Site users are members of which demographic groups), subject to the rest of this privacy policy. When you respond to an advertisement, however, we ask you to remember that if that ad that is targeted to a demographic group and you decide to give the advertiser your personal information, then the advertiser may be able to identify you as being a member of that demographic group.
        </p>
        <h3> How to Edit Your Information</h3>
        <p>
          Mycollegeadda.com believes strongly in giving you the ability to access and edit your personal information. In My Account Tab, you can view, update and correct your account information. You may edit your profile at any time -- all you need is your username and password.
        So that we can protect the integrity of sensitive data, there are certain pieces of information, such as your age, that you cannot alter yourself. For example, since children under 18 are not allowed to register as Mycollegeadda.com members, we need to take reasonable measures to preserve the accuracy of our members' ages. Please contact us at support@Mycollegeadda.com to find out how to change information you cannot access through your Profile.
        Our databases automatically update any personal information you edit in your profile, or that you request we edit. Information transmitted through boards, chats, polls or through any other means remain in our databases and become the property of Mycollegeadda.com upon submission. Keep this in mind if you decide to communicate personal information through any of these applications.
        </p>
        <h3> Information Retention</h3>
        <p>
        To preserve the integrity of our databases, standard procedure calls for us to retain information submitted by members for an indefinite length of time. Mycollegeadda.com understands your submissions as consent to store all your information in one place for this indefinite length of time, if we so wish. If required by law, we will nullify member information by erasing it from our database. We will also respond to written member requests to nullify account information. If you wish to make such a request, which requires that we verify your identity, or if you have any questions regarding this policy, contact Mycollegeadda.com at support@Mycollegeadda.com. Also, by using this site, you do hereby represent and warrant that you understand and agree that all information submitted by you to Mycollegeadda.com becomes the property of Mycollegeadda.com and may be used in the sole discretion of Mycollegeadda.com in accordance with this Privacy Policy and the Terms of Use.
        </p>
        <h3> Choice/Opt-Out</h3>
        <p>
        Our site provides users the opportunity to opt-out of receiving communications from us and our partners at the point where we request information about the visitor. This site gives users the option to remove their information from our database, to not receive future communications or to no longer receive our service.
        </p>
        <h3> Special Cases in which we Share Personal Information</h3>
        <p>
          Your personal information may be passed on to a third party in the event of a transfer of ownership or assets, or a bankruptcy. We may also disclose personal information when we determine that such disclosure is necessary to comply with applicable law, to cooperate with law enforcement or to protect the interests or safety of users, the Site, or other visitors to the Site. We also may disclose your personal information to our subsidiary and parent companies and businesses, and other affiliated legal entities and businesses with whom we are under common corporate control. Whenever personal information is disclosed under this paragraph, we may also disclose your demographic information along with it, on a non-anonymous basis. All of our parent, subsidiary and affiliated legal entities and businesses that receive your personal information or non-anonymous demographic information from us will comply with the terms of this privacy policy with respect to their use and disclosure of such information.
        </p>
        <h3> Our Security Precautions</h3>
        <p>
          Your Mycollegeadda.com Profile is password-protected so that only you and authorized Mycollegeadda.com employees have access to your account information. In order to maintain this protection, do not give your password to anyone. If someone who represents to you they are Mycollegeadda.com staff asks for any personal account information, including password, check their URL. If it doesn't say they are support@Mycollegeadda.com, they're not. Also, if you share a computer, you should sign out of your Mycollegeadda.com account and close the browser window before someone else logs on. This will help protect your information entered on public terminals from disclosure to third parties.
        Mycollegeadda.com makes every effort to ensure that your information is secure on its system. Mycollegeadda.com has staff dedicated to maintaining this Privacy Policy and other privacy initiatives, periodically reviewing Web security and making sure that every Mycollegeadda.com employee is aware of our security practices. Unfortunately, no data transmission over the Internet can be guaranteed to be 100% secure. As a result, Mycollegeadda.com cannot guarantee the security of any information you transmit to us, and you do so at your own risk. If you have any further questions on this issue, refer to the site Terms of Use. Mycollegeadda.com expressly disclaims any liability that may arise should any other individuals obtain the information you submit to this site.
        The Site has security measures in place to protect against the loss, misuse and alteration of the information under our control. Your information may be transferred to and maintained on computer networks which may be located outside of the state, province, country or other governmental jurisdiction in which you reside, and the country or jurisdiction in which these computer networks are located may not have privacy laws as protective as the laws in your country or jurisdiction.
        Mycollegeadda.com may contain links to other websites. We are of course not responsible for the privacy practices of other web sites. We encourage our users to be aware when they leave our site to read the privacy statements of each and every web site that collects personally identifiable information. This Privacy Policy applies solely to information collected by Mycollegeadda.com.
        </p>
        <h3> Changing our Privacy Policy for Previously Gathered Information</h3>
        <p>
          If at any point we decide to use particular personally identifiable information in a manner materially different from that stated at the time it was collected, we will notify users by way of an email or by providing 30 days notice on the Site. Mycollegeadda.com also encourages you to review this privacy policy periodically. By using the site, you do hereby represent and warrant that you have read, understand and agree to all terms of this Privacy Policy and Terms of Service. Each time you use the site, you agree to all terms set forth by Mycollegeadda.com in both its Privacy Policy and Terms of Service and any other policies published by Mycollegeadda.com on the site. If you do not understand any of the terms or conditions of any of Mycollegeadda.com's policies, you may inquire regarding the same via electronic correspondence (e-mail) at support@Mycollegeadda.com. Please note that we will continue to have the right to change our privacy policy and practices, and how we use your personally identifiable information, without notice, as described in the first paragraph of this Privacy Policy, provided that such changes shall only apply to information gathered on or after the date of the change.
        </p>
        <h3> Contacting the Web Site</h3>
        <p>
          If you have any questions about this privacy statement, the practices of this site, or your dealings with this Web site, you may contact us at support@Mycollegeadda.com.
        </p>
        </article>
</section>
@stop